<?php

namespace App\Models;

use App\Services\Uploader\StorageManager;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class File extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleted(function ($file) {
            resolve(StorageManager::class)->deleteFile($file->name, $file->type, $file->is_private);
        });
    }

    public function download()
    {
        return resolve(StorageManager::class)->getFile($this->name, $this->type, $this->is_private);
    }

//    /*
//     * @Override delete method
//     */
//    public function delete()
//    {
//        resolve(StorageManager::class)->deleteFile($this->name, $this->type, $this->is_private);
//        parent::delete();
//    }
}
